# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.4.2
_src_path: gh:algorandfoundation/algokit-python-template
author_email: cosimo.bassi@gmail.com
author_name: cusma
contract_name: base_d_asa
deployment_language: python
preset_name: production
project_name: d-asa

