name: Validate docs

on:
  workflow_call:
  pull_request:
    # If not specified, types includes by default [opened, reopened, synchronize]
    # This next line should be used in conjunction with the if statement that prevents CI jobs to run on draft PRs.
    # ready_for_review is then added to make sure that a PR with no code change triggers CI if it's no longer a draft PR.
    types: [ opened, reopened, synchronize, ready_for_review ]
    paths:
      - 'docs/**'

permissions:
  contents: read

jobs:
  validate:
    name: Validate docs
    # Preventing a job from running on draft PRs.
    if: '! github.event.pull_request.draft'
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: '0.4.43'

      - name: Build docs
        run: mdbook build

      - name: Test docs
        run: mdbook test

      - name: Check markdown linting
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: markdownlint

      - name: Check trailing whitespaces
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: trailing-whitespace
